project:
  type: website

website:
  title: "Yeye's Research Handbook"
  sidebar:
    style: docked
    search: true
    contents:
      - home.qmd
      - research.qmd
      - methods.qmd
      - code.qmd
      - reading.qmd

format:
  html:
    theme: cosmo
    toc: true
    smooth-scroll: true