project:
  type: website
  output-dir: docs

website:
  title: "Yeye's Research Handbook"
  sidebar:
    style: docked
    search: true
    contents:
      - home.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    toc: true
    smooth-scroll: true